import React from 'react';
import { useDetection, Detection } from '@/contexts/DetectionContext';
import {
  X, AlertTriangle, CheckCircle2, Image, Video, Music,
  Shield, FileWarning, Fingerprint, Clock, Globe, ChevronRight, Download
} from 'lucide-react';

const DetectionDetail: React.FC = () => {
  const { selectedDetection, setSelectedDetection } = useDetection();

  if (!selectedDetection) return null;
  const d = selectedDetection;

  const getConfidenceColor = (conf: number) => {
    if (conf > 80) return { text: 'text-red-400', bg: 'bg-red-500', bgLight: 'bg-red-500/10', border: 'border-red-500/30' };
    if (conf > 50) return { text: 'text-orange-400', bg: 'bg-orange-500', bgLight: 'bg-orange-500/10', border: 'border-orange-500/30' };
    if (conf > 25) return { text: 'text-yellow-400', bg: 'bg-yellow-500', bgLight: 'bg-yellow-500/10', border: 'border-yellow-500/30' };
    return { text: 'text-green-400', bg: 'bg-green-500', bgLight: 'bg-green-500/10', border: 'border-green-500/30' };
  };

  const colors = getConfidenceColor(d.ai_confidence);

  const getMediaIcon = () => {
    switch (d.media_type) {
      case 'video': return <Video className="w-5 h-5" />;
      case 'audio': return <Music className="w-5 h-5" />;
      default: return <Image className="w-5 h-5" />;
    }
  };

  return (
    <div className="fixed inset-0 z-[60] flex items-center justify-center p-4 bg-black/70 backdrop-blur-sm" onClick={() => setSelectedDetection(null)}>
      <div className="w-full max-w-2xl max-h-[90vh] overflow-y-auto bg-gray-900 border border-gray-700 rounded-2xl shadow-2xl" onClick={e => e.stopPropagation()}>
        <div className="relative">
          {d.thumbnail_url && (
            <div className="h-48 overflow-hidden rounded-t-2xl">
              <img src={d.thumbnail_url} alt={d.title} className="w-full h-full object-cover" />
              <div className="absolute inset-0 bg-gradient-to-t from-gray-900 via-gray-900/50 to-transparent" />
            </div>
          )}
          <button
            onClick={() => setSelectedDetection(null)}
            className="absolute top-4 right-4 p-2 rounded-lg bg-gray-900/80 text-gray-400 hover:text-white hover:bg-gray-800 transition-colors backdrop-blur-sm"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="p-6 space-y-6">
          <div className="flex items-start justify-between gap-4">
            <div>
              <h2 className="text-xl font-bold text-white">{d.title}</h2>
              <div className="flex items-center gap-3 mt-2 text-sm text-gray-400">
                <span className="flex items-center gap-1">{getMediaIcon()} {d.media_type}</span>
                <span className="flex items-center gap-1"><Globe className="w-4 h-4" /> {d.source_platform}</span>
                <span className="flex items-center gap-1"><Clock className="w-4 h-4" /> {new Date(d.scanned_at).toLocaleString()}</span>
              </div>
            </div>
          </div>

          <div className={`p-5 rounded-xl ${colors.bgLight} border ${colors.border}`}>
            <div className="flex items-center justify-between mb-3">
              <div className="flex items-center gap-3">
                {d.is_ai_generated ? (
                  <AlertTriangle className={`w-6 h-6 ${colors.text}`} />
                ) : (
                  <CheckCircle2 className="w-6 h-6 text-green-400" />
                )}
                <div>
                  <div className={`text-lg font-bold ${d.is_ai_generated ? colors.text : 'text-green-400'}`}>
                    {d.is_ai_generated ? 'AI-Generated Content Detected' : 'Content Appears Authentic'}
                  </div>
                  <div className="text-sm text-gray-400">
                    {d.ai_model_detected && d.ai_model_detected !== 'N/A - Authentic'
                      ? `Likely generated by: ${d.ai_model_detected}`
                      : 'No AI generation signatures found'}
                  </div>
                </div>
              </div>
              <div className={`text-3xl font-extrabold ${colors.text}`}>{d.ai_confidence}%</div>
            </div>
            <div className="h-3 bg-gray-800 rounded-full overflow-hidden">
              <div className={`h-full ${colors.bg} rounded-full transition-all duration-1000`} style={{ width: `${d.ai_confidence}%` }} />
            </div>
            <div className="flex justify-between mt-1 text-xs text-gray-500">
              <span>Authentic</span>
              <span>AI Generated</span>
            </div>
          </div>

          {d.detection_details?.analysis_summary && (
            <div className="p-4 rounded-xl bg-gray-800/50 border border-gray-700/50">
              <h3 className="text-sm font-semibold text-white mb-2 flex items-center gap-2">
                <Shield className="w-4 h-4 text-cyan-400" />
                Analysis Summary
              </h3>
              <p className="text-sm text-gray-300 leading-relaxed">{d.detection_details.analysis_summary}</p>
            </div>
          )}

          {d.detection_details?.artifacts && d.detection_details.artifacts.length > 0 && (
            <div>
              <h3 className="text-sm font-semibold text-white mb-3 flex items-center gap-2">
                <FileWarning className="w-4 h-4 text-orange-400" />
                Detected Artifacts ({d.detection_details.artifacts.length})
              </h3>
              <div className="space-y-2">
                {d.detection_details.artifacts.map((artifact, i) => (
                  <div key={i} className="flex items-center gap-3 p-3 rounded-lg bg-gray-800/50 border border-gray-700/30">
                    <div className="w-6 h-6 rounded-full bg-orange-500/20 flex items-center justify-center flex-shrink-0">
                      <span className="text-xs text-orange-400 font-bold">{i + 1}</span>
                    </div>
                    <span className="text-sm text-gray-300">{artifact}</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {d.detection_details?.metadata_flags && d.detection_details.metadata_flags.length > 0 && (
            <div>
              <h3 className="text-sm font-semibold text-white mb-3 flex items-center gap-2">
                <Fingerprint className="w-4 h-4 text-purple-400" />
                Metadata Analysis
              </h3>
              <div className="flex flex-wrap gap-2">
                {d.detection_details.metadata_flags.map((flag, i) => (
                  <span key={i} className="px-3 py-1.5 rounded-lg bg-purple-500/10 border border-purple-500/20 text-purple-300 text-xs font-medium">
                    {flag}
                  </span>
                ))}
              </div>
            </div>
          )}

          <div className="flex gap-3 pt-2">
            <button
              onClick={() => {
                const report = `Lucid Detection Report\n${'='.repeat(40)}\nTitle: ${d.title}\nMedia Type: ${d.media_type}\nSource: ${d.source_platform}\nAI Confidence: ${d.ai_confidence}%\nModel: ${d.ai_model_detected}\nVerdict: ${d.is_ai_generated ? 'AI Generated' : 'Authentic'}\nArtifacts: ${d.detection_details?.artifacts?.join(', ') || 'None'}\nMetadata: ${d.detection_details?.metadata_flags?.join(', ') || 'None'}`;
                const blob = new Blob([report], { type: 'text/plain' });
                const url = URL.createObjectURL(blob);
                const a = document.createElement('a');
                a.href = url;
                a.download = `detection-report-${d.id}.txt`;
                a.click();
                URL.revokeObjectURL(url);
              }}
              className="flex-1 flex items-center justify-center gap-2 px-4 py-3 bg-cyan-500/10 border border-cyan-500/30 text-cyan-400 rounded-xl font-medium text-sm hover:bg-cyan-500/20 transition-colors"
            >
              <Download className="w-4 h-4" />
              Download Report
            </button>
            <button
              onClick={() => setSelectedDetection(null)}
              className="flex-1 flex items-center justify-center gap-2 px-4 py-3 bg-gray-800 border border-gray-700 text-gray-300 rounded-xl font-medium text-sm hover:bg-gray-700 transition-colors"
            >
              Close
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default DetectionDetail;
